### ISSUE TITLE
Uncaught TypeError: form.files is null

### ISSUE THREAD

**Issue by AlvinSetyaPranata** [pamekasancode/Validate_Js#3]
i've tested in a simple page but unfortuantelly the there is an error occured when i want to submit the form which **Uncaught TypeError: form.files is null**, can you please fix this problem?

**Comment by firmansyahken** [comment]
Share ur code i think we dont have problem with library

**Comment by firmansyahken** [comment]
thankyou for the issue, i fixed it now
